[obs]
bundle_project = "systemsmanagement:saltstack:bundle"
api_baseurl = "https://api.opensuse.org"

[github]
repo = "SUSE/spacewalk"
project_board_id = "PVT_kwDOABBK1c4AO0-4"
[github.issue]
title = "Update Salt Bundle Dependencies"
body = """
It's time to update all dependencies in the Salt Bundle.

At the time of creating this card ($now), there have been these updates since $last_execution:

$updates

Please use `echo $last_execution_ts >.last_execution && lubed updates` for an up-to-date list.

_This issue was generated automatically._
"""
labels = ["ion-squad", "salt-bundle"]

[origins]
[origins.saltbundlepy]
project = "SUSE:SLE-15-SP6:Update"
package = "python311"
[origins.saltbundle-libffi]
project = "SUSE:SLE-15-SP5:GA"
package = "libffi_3_4"
[origins.saltbundle-libsodium]
project = "SUSE:SLE-15-SP4:Update"
package = "libsodium"
[origins.saltbundle-libyaml]
project = "SUSE:SLFO:1.2"
package = "libyaml"
[origins.saltbundle-openssl]
project = "SUSE:SLE-12-SP5:Update"
package = "openssl"
[origins.saltbundle-swig]
project = "SUSE:SLE-15-SP6:Update"
package = "swig"
[origins.saltbundle-zeromq]
project = "SUSE:SLE-15-SP4:Update"
package = "zeromq"
[origins.saltbundlepy-appdirs]
project = "SUSE:SLE-15-SP4:Update"
package = "python-appdirs"
[origins.saltbundlepy-asn1crypto]
project = "SUSE:SLE-15-SP4:Update"
package = "python-asn1crypto"
[origins.saltbundlepy-atomicwrites]
project = "SUSE:SLE-15-SP4:Update"
package = "python-atomicwrites"
[origins.saltbundlepy-attrs]
project = "SUSE:SLE-15-SP4:Update"
package = "python-attrs"
[origins.saltbundlepy-bcrypt]
project = "SUSE:SLE-15-SP4:Update"
package = "python-bcrypt"
[origins.saltbundlepy-certifi]
project = "SUSE:SLE-15-SP4:Update"
package = "python-certifi"
[origins.saltbundlepy-cffi]
project = "SUSE:SLE-15-SP4:Update"
package = "python-cffi"
[origins.saltbundlepy-chardet]
project = "SUSE:SLE-15-SP4:Update"
package = "python-chardet"
[origins.saltbundlepy-cryptography]
project = "SUSE:SLE-15-SP4:Update"
package = "python-cryptography"
[origins.saltbundlepy-cryptography-vectors]
project = "SUSE:SLE-15-SP4:Update"
package = "python3-cryptography-vectors"
[origins.saltbundlepy-cssselect]
project = "SUSE:SLE-15-SP4:Update"
package = "python-cssselect"
[origins.saltbundlepy-cython]
project = "SUSE:SLFO:1.2"
package = "python-Cython"
[origins.saltbundlepy-dateutil]
project = "SUSE:SLE-15-SP4:Update"
package = "python-python-dateutil"
[origins.saltbundlepy-dbus-python]
project = "SUSE:SLE-15-SP6:Update"
package = "python-dbus-python"
[origins.saltbundlepy-distro]
project = "SUSE:SLE-15-SP4:Update"
package = "python-distro"
[origins.saltbundlepy-docker]
project = "SUSE:SLE-15-SP4:Update"
package = "python-docker"
[origins.saltbundlepy-docker-pycreds]
project = "openSUSE:Factory"
package = "python-docker-pycreds"
[origins.saltbundlepy-docopt]
project = "SUSE:SLE-15-SP4:Update"
package = "python-docopt"
[origins.saltbundlepy-editables]
project = "SUSE:SLE-15-SP4:Update"
package = "python-editables"
[origins.saltbundlepy-exceptiongroup]
project = "SUSE:SLE-15-SP4:Update"
package = "python-exceptiongroup"
[origins.saltbundlepy-flit-core]
project = "SUSE:SLE-15-SP4:Update"
package = "python-flit-core"
[origins.saltbundlepy-flit-scm]
project = "SUSE:SLE-15-SP4:Update"
package = "python-flit-scm"
[origins.saltbundlepy-hatch-fancy-pypi-readme]
project = "SUSE:SLE-15-SP4:Update"
package = "python-hatch-fancy-pypi-readme"
[origins.saltbundlepy-hatch-vcs]
project = "SUSE:SLE-15-SP4:Update"
package = "python-hatch-vcs"
[origins.saltbundlepy-hatchling]
project = "SUSE:SLE-15-SP4:Update"
package = "python-hatchling"
[origins.saltbundlepy-idna]
project = "SUSE:SLE-15-SP4:Update"
package = "python-idna"
[origins.saltbundlepy-importlib-metadata]
project = "SUSE:SLE-15-SP4:Update"
package = "python-importlib-metadata"
[origins.saltbundlepy-iniconfig]
project = "SUSE:SLE-15-SP4:Update"
package = "python-iniconfig"
[origins.saltbundlepy-jinja2]
project = "SUSE:SLE-15-SP4:Update"
package = "python-Jinja2"
[origins.saltbundlepy-jmespath]
project = "SUSE:SLE-15-SP4:Update"
package = "python-jmespath"
[origins.saltbundlepy-kiwi]
project = "SUSE:SLE-15-SP4:Update"
package = "python-kiwi"
[origins.saltbundlepy-libvirt]
project = "SUSE:SLE-15-SP4:Update"
package = "python-libvirt-python"
[origins.saltbundlepy-looseversion]
project = "SUSE:SLE-15-SP4:Update"
package = "python-looseversion"
[origins.saltbundlepy-lxml]
project = "SUSE:SLFO:1.2"
package = "python-lxml"
[origins.saltbundlepy-m2crypto]
project = "SUSE:SLE-15-SP4:Update"
package = "python3-M2Crypto"
[origins.saltbundlepy-markupsafe]
project = "SUSE:SLFO:1.2"
package = "python-MarkupSafe"
[origins.saltbundlepy-more-itertools]
project = "SUSE:SLE-15-SP4:Update"
package = "python-more-itertools"
[origins.saltbundlepy-msgpack]
project = "SUSE:SLFO:1.2"
package = "python-msgpack"
[origins.saltbundlepy-netaddr]
project = "SUSE:SLE-15-SP4:Update"
package = "python-netaddr"
[origins.saltbundlepy-packaging]
project = "SUSE:SLE-15-SP4:Update"
package = "python-packaging"
[origins.saltbundlepy-paramiko]
project = "SUSE:SLE-15-SP4:Update"
package = "python-paramiko"
[origins.saltbundlepy-passlib]
project = "SUSE:SLE-15-SP6:GA"
package = "python-passlib"
[origins.saltbundlepy-pathspec]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pathspec"
[origins.saltbundlepy-pip]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pip"
[origins.saltbundlepy-pluggy]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pluggy"
[origins.saltbundlepy-ply]
project = "SUSE:SLE-15-SP4:Update"
package = "python-ply"
[origins.saltbundlepy-psutil]
project = "SUSE:SLFO:1.2"
package = "python-psutil"
[origins.saltbundlepy-ptyprocess]
project = "SUSE:SLE-15-SP4:Update"
package = "python-ptyprocess"
[origins.saltbundlepy-py]
project = "SUSE:SLE-15-SP4:Update"
package = "python-py"
[origins.saltbundlepy-pyasn1]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pyasn1"
[origins.saltbundlepy-pyasn1-modules]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pyasn1-modules"
[origins.saltbundlepy-pycparser]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pycparser"
[origins.saltbundlepy-pycurl]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pycurl"
[origins.saltbundlepy-pyinotify]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pyinotify"
[origins.saltbundlepy-pynacl]
project = "SUSE:SLE-15-SP4:Update"
package = "python-PyNaCl"
[origins.saltbundlepy-pyopenssl]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pyOpenSSL"
[origins.saltbundlepy-pyparsing]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pyparsing"
[origins.saltbundlepy-pysocks]
project = "SUSE:SLE-15-SP4:Update"
package = "python-PySocks"
[origins.saltbundlepy-pytest]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pytest"
[origins.saltbundlepy-pytz]
project = "SUSE:SLE-15-SP4:Update"
package = "python-pytz"
[origins.saltbundlepy-pyxattr]
project = "openSUSE:Factory"
package = "python-pyxattr"
[origins.saltbundlepy-pyyaml]
project = "SUSE:SLFO:1.2"
package = "python-PyYAML"
[origins.saltbundlepy-pyzmq]
project = "SUSE:SLFO:1.2"
package = "python-pyzmq"
[origins.saltbundlepy-requests]
project = "SUSE:SLE-15-SP4:Update"
package = "python-requests"
[origins.saltbundlepy-rpm-macros]
project = "SUSE:SLE-15-SP4:Update"
package = "python-rpm-macros"
[origins.saltbundlepy-setuptools]
project = "SUSE:SLFO:1.2"
package = "python-setuptools"
[origins.saltbundlepy-setuptools-scm]
project = "SUSE:SLFO:1.2"
package = "python-setuptools_scm"
[origins.saltbundlepy-simplejson]
project = "SUSE:SLE-15-SP4:Update"
package = "python-simplejson"
[origins.saltbundlepy-six]
project = "SUSE:SLFO:1.2"
package = "python-six"
[origins.saltbundlepy-tomli]
project = "SUSE:SLE-15-SP4:Update"
package = "python-tomli"
[origins.saltbundlepy-tornado]
project = "SUSE:SLE-15-SP4:Update"
package = "python-tornado"
[origins.saltbundlepy-typing-extensions]
project = "SUSE:SLE-15-SP6:GA"
package = "python-typing_extensions"
[origins.saltbundlepy-urllib3]
project = "SUSE:SLE-15-SP4:Update"
package = "python-urllib3"
[origins.saltbundlepy-wcwidth]
project = "SUSE:SLE-15-SP5:Update"
package = "python-wcwidth"
[origins.saltbundlepy-websocket-client]
project = "SUSE:SLE-15-SP4:Update"
package = "python-websocket-client"
[origins.saltbundlepy-wheel]
project = "SUSE:SLFO:1.2"
package = "python-wheel"
[origins.saltbundlepy-zipp]
project = "SUSE:SLE-15-SP4:Update"
package = "python-zipp"
[origins.saltbundlepy-zypp-plugin]
project = "SUSE:SLE-15-SP4:Update"
package = "zypp-plugin"
